### ISSUE TITLE
Error: Cannot find module 'svelte-select'

### ISSUE THREAD

**Issue by nielk** [rob-balfre/svelte-select#559]
Hello, since I updated from 5.2.1 to 5.3.0 I get the following error:

<img width="655" alt="Capture d’écran 2023-02-21 à 08 55 22" src="https://user-images.githubusercontent.com/4980521/220283028-7ded4742-cb5e-4536-80c8-54c9672ec028.png">

If I downgrade to 5.2.1 it works. Do you know how I can fix that ?

Thanks

**Comment by rob-balfre** [comment]
What setup do you have? SvelteKit?

**Comment by nielk** [comment]
typescript + svelte + rollup

here is my tsconfig:
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "types": ["svelte", "mocha"],
    "strict": true,
    "noImplicitAny": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "removeComments": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "pretty": true,
    "allowJs": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "importsNotUsedAsValues": "error",
    "noUncheckedIndexedAccess": true,
    "baseUrl": ".",
    "paths": {
      "_/*": ["./src/*"]
    }
  },
  "include": [
    "src/**/*",
    "test/**/*",
    "build/**/*"
  ],
  "exclude": ["node_modules"]
}

```

**Comment by rob-balfre** [comment]
Anything in your roll-up to alias the old svelte-select?

**Comment by rob-balfre** [comment]
I'm gonna revert the build change. Sorry about that. It's a breaking change
that needs a major version bump.

Thanks for reporting.

**Comment by nielk** [comment]
No worries, thanks for your responsiveness :)

I would appreciate it if you could have a changelog and/or migration guide for any breaking change version

**Comment by rob-balfre** [comment]
@nielk yeah was an accidental break - my bad.  Fixed in `5.3.1`

**Comment by nielk** [comment]
@rob-balfre Thanks, I updated to 5.3.1 and everything goes well :)
